language: php

dist: trusty
php:
    - '8.0'
    - '7.4'
    - '7.3'
    - '7.2'
    - '7.1'
    - '7.0'
    - '5.6'

before_script:
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction --prefer-source

script:
    - phpcs --standard=PSR2 src
    - phpunit --verbose --coverage-clover coverage.clover

after_success:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
